public enum ErrorType {

    VARIABLE_DEFINED,

    VARIABLE_NOT_DEFINED,

    FUNCTION_DEFINED,

	  FUNCTION_NOT_DEFINED,

    FUNCTION_NOT_RETURNS,

    ADDITION_WITH_DIFFERENT_TYPES,

    NON_INTEGER_DECIMAL_SUBSTRACTION,

    NON_INTEGER_DECIMAL_MULTIPLICATION,

    NON_INTEGER_DECIMAL_DIVISION,

    NON_INTEGER_DECIMAL_EXPONENTIATION,

    ARGUMENT_NOT_PERMITTED

}
